# Generated by Django 5.2.16 on 2026-07-20 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('module', models.CharField(choices=[('AUTH', 'Authentication'), ('STUDENT', 'Student Management'), ('STAFF', 'Staff Management'), ('ACADEMIC', 'Academic'), ('ASSESSMENT', 'Assessment'), ('FINANCE', 'Finance'), ('ATTENDANCE', 'Attendance'), ('TIMETABLE', 'Timetable'), ('REPORT', 'Reports'), ('LOGBOOK', 'Logbook'), ('NOTIFICATION', 'Notifications'), ('DOCUMENT', 'Documents'), ('SYSTEM', 'System'), ('GOVERNMENT', 'Government')], max_length=20)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
