# Generated by Django 5.2.16 on 2026-08-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinvoice',
            options={'ordering': ['-created_at', '-invoice_number']},
        ),
    ]
