# Generated by Django 5.2.16 on 2026-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_studentinvoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount_paid_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of the invoice's cumulative amount paid after this transaction. Used so receipts always print the correct running balance for an installment.", max_digits=12, null=True),
        ),
    ]
