# Generated by Django 5.2.16 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_amount_paid_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='fee_category',
            field=models.ForeignKey(
                blank=True,
                help_text='What kind of fee this payment was for (Tuition, Registration, etc.)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payment_transactions',
                to='finance.feecategory',
            ),
        ),
    ]
