# Generated by Django 5.2.16 on 2026-08-17 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_class_fatigue_sensitivity_and_more'),
        ('finance', '0004_paymenttransaction_fee_category'),
        ('students', '0006_student_middle_name'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['tenant', 'academic_year'], name='idx_feestructure_tenant_yr'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['invoice'], name='idx_payment_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['student', 'academic_year'], name='idx_invoice_student_year_term'),
        ),
    ]
