/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#264191",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006b5f",
        "surface-tint": "#4059aa",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b6c4ff",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "tertiary": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "outline": "#757682",
        "on-secondary-fixed-variant": "#005048",
        "on-surface-variant": "#444651",
        "primary": "#00236f",
        "secondary-fixed": "#71f8e4",
        "background": "#f7f9fb",
        "outline-variant": "#c5c5d3",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed": "#00201c",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "tertiary-container": "#5c3800",
        "secondary-container": "#6df5e1",
        "on-primary-container": "#90a8ff",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006f64",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "primary-container": "#1e3a8a",
        "secondary-fixed-dim": "#4fdbc8",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-container": "#ef9900",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#dce1ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00164e"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'premium': '0 24px 48px -12px rgba(0, 0, 0, 0.04)',
      },
      backgroundImage: {
        'gradient-premium': 'linear-gradient(135deg, #00236f 0%, #1e3a8a 100%)',
      }
    },
  },
  plugins: [],
}
