/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "blue": {
          "50": "rgb(var(--color-blue-50) / <alpha-value>)",
          "100": "rgb(var(--color-blue-100) / <alpha-value>)",
          "200": "rgb(var(--color-blue-200) / <alpha-value>)",
          "300": "rgb(var(--color-blue-300) / <alpha-value>)",
          "400": "rgb(var(--color-blue-400) / <alpha-value>)",
          "500": "rgb(var(--color-blue-500) / <alpha-value>)",
          "600": "rgb(var(--color-blue-600) / <alpha-value>)",
          "700": "rgb(var(--color-blue-700) / <alpha-value>)",
          "800": "rgb(var(--color-blue-800) / <alpha-value>)",
          "900": "rgb(var(--color-blue-900) / <alpha-value>)",
        },
        "indigo": {
          "50": "rgb(var(--color-indigo-50) / <alpha-value>)",
          "100": "rgb(var(--color-indigo-100) / <alpha-value>)",
          "200": "rgb(var(--color-indigo-200) / <alpha-value>)",
          "300": "rgb(var(--color-indigo-300) / <alpha-value>)",
          "400": "rgb(var(--color-indigo-400) / <alpha-value>)",
          "500": "rgb(var(--color-indigo-500) / <alpha-value>)",
          "600": "rgb(var(--color-indigo-600) / <alpha-value>)",
          "700": "rgb(var(--color-indigo-700) / <alpha-value>)",
          "800": "rgb(var(--color-indigo-800) / <alpha-value>)",
          "900": "rgb(var(--color-indigo-900) / <alpha-value>)",
        },
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#264191",
        "on-error": "#ffffff",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-surface-tint) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b6c4ff",
        "inverse-surface": "#2d3133",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "error": "#ba1a1a",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "tertiary": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "on-secondary-fixed-variant": "#005048",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "secondary-fixed": "#71f8e4",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed": "#00201c",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "tertiary-container": "#5c3800",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "on-error-container": "#93000a",
        "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "on-tertiary": "#ffffff",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "secondary-fixed-dim": "#4fdbc8",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-container": "#ef9900",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "primary-fixed": "#dce1ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00164e"
      },
      fontFamily: {
        "headline": "var(--font-headline, 'Inter', 'Segoe UI', sans-serif)",
        "body": "var(--font-body, 'Inter', 'Segoe UI', sans-serif)",
        "label": "var(--font-body, 'Inter', 'Segoe UI', sans-serif)",
        "inter": "var(--font-body, 'Inter', 'Segoe UI', sans-serif)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'premium': '0 24px 48px -12px rgba(0, 0, 0, 0.04)',
      },
      backgroundImage: {
        'gradient-premium': 'linear-gradient(135deg, rgb(var(--color-primary)) 0%, rgb(var(--color-primary-container)) 100%)',
      }
    },
  },
  plugins: [],
}
