# Generated by Django 5.2.16 on 2026-08-15 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenantconfig_finance_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine Inspection'), ('follow_up', 'Follow-up Inspection'), ('complaint', 'Complaint-Based Inspection'), ('accreditation', 'Accreditation Review'), ('special', 'Special Audit')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('report_draft', 'Report Draft'), ('report_finalized', 'Report Finalized'), ('closed', 'Closed')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('critical', 'Critical Non-Compliance'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('scope_notes', models.TextField(blank=True, help_text='Areas to be inspected')),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text="Specific focus areas (e.g., ['attendance', 'curriculum', 'finance'])")),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall compliance score (0-100)', max_digits=5, null=True)),
                ('summary', models.TextField(blank=True, help_text='Executive summary of findings')),
                ('recommendations', models.TextField(blank=True, help_text='Key recommendations')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='inspection_reports/')),
                ('report_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspectors', models.ManyToManyField(blank=True, limit_choices_to={'is_government_official': True}, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('lead_inspector', models.ForeignKey(blank=True, limit_choices_to={'is_government_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_inspections', to=settings.AUTH_USER_MODEL)),
                ('report_finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='School being inspected', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tenants.tenant')),
            ],
            options={
                'db_table': 'government_inspections',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('school_policy', 'School Policy'), ('curriculum_plan', 'Curriculum Plan / Scheme of Work'), ('timetable', 'Class Timetables'), ('staff_records', 'Staff Records / Qualifications'), ('student_records', 'Student Records / Admissions'), ('attendance_registers', 'Attendance Registers'), ('assessment_records', 'Assessment / Exam Records'), ('financial_records', 'Financial Records'), ('infrastructure', 'Infrastructure / Safety Certificates'), ('governance', 'Governance / Board Minutes'), ('inspection_evidence', 'Inspection Evidence (photos, notes)'), ('correspondence', 'Official Correspondence'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='inspection_documents/')),
                ('is_confidential', models.BooleanField(default=False, help_text='Restrict to inspectors only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='government.inspection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'government_inspection_documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('governance', 'Governance & Leadership'), ('curriculum', 'Curriculum & Instruction'), ('teaching', 'Teaching Quality'), ('learning', 'Learning Outcomes'), ('assessment', 'Assessment & Examinations'), ('attendance', 'Attendance & Retention'), ('safeguarding', 'Safeguarding & Welfare'), ('infrastructure', 'Infrastructure & Resources'), ('finance', 'Financial Management'), ('staffing', 'Staffing & Professional Development'), ('data', 'Data & Reporting'), ('compliance', 'Statutory Compliance')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation'), ('good_practice', 'Good Practice')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the finding')),
                ('evidence', models.TextField(blank=True, help_text='Evidence supporting the finding')),
                ('reference_standard', models.CharField(blank=True, help_text="Regulatory reference (e.g., 'MINESEC Circular 2023/045', 'Education Law Art. 12')", max_length=255)),
                ('recommended_action', models.TextField(blank=True, help_text='Recommended corrective action')),
                ('deadline', models.DateField(blank=True, help_text='Deadline for corrective action', null=True)),
                ('responsible_party', models.CharField(blank=True, help_text="Who is responsible (e.g., 'Principal', 'Bursar', 'Board of Governors')", max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_findings', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='government.inspection')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'government_inspection_findings',
                'ordering': ['severity', 'category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField(help_text='Description of corrective action taken')),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='List of uploaded evidence file URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected - More Work Needed'), ('verified', 'Verified & Closed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_government_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='School staff who submitted the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='government.inspectionfinding')),
            ],
            options={
                'db_table': 'government_corrective_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('termly', 'Per Term'), ('ad_hoc', 'Ad Hoc Only')], default='annual', max_length=20)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('preferred_months', models.JSONField(blank=True, default=list, help_text='Preferred months for inspection (1-12)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedule', to='tenants.tenant')),
            ],
            options={
                'db_table': 'government_inspection_schedules',
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['tenant', 'status'], name='government__tenant__df044f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['lead_inspector', 'status'], name='government__lead_in_190235_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['scheduled_date'], name='government__schedul_14fa8e_idx'),
        ),
    ]
