# Generated by Django 5.2.16 on 2026-08-08 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.announcement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_reads',
                'constraints': [models.UniqueConstraint(fields=('user', 'announcement'), name='uniq_announcement_read_user')],
            },
        ),
    ]
