# Generated by Django 5.2.16 on 2026-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0006_student_middle_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='idx_attend_sess_status'),
        ),
    ]
