# Generated by Django 5.2.16 on 2026-07-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='Notable achievements or awards'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('available', 'Available for Hire')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed average from reviews', max_digits=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text="List of certifications, e.g. ['BSc Mathematics', 'TEFL']"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. Science, Arts, Languages', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for marketplace (XAF)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['English', 'French']"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='Show profile in the national teacher marketplace'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text="List of specialization tags, e.g. ['Physics', 'AP Calculus']"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.JSONField(blank=True, default=list, help_text='Flat list of subject names for marketplace display'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_philosophy',
            field=models.TextField(blank=True, help_text='Short statement about teaching approach'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
