# Generated by Django 5.2.16 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
        ('staff', '0002_teacher_achievements_teacher_availability_and_more'),
        ('tenants', '0003_tenant_idx_tenant_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['teacher', 'academic_year'], name='idx_assignment_teacher'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['tenant', 'academic_class'], name='idx_assignment_class'),
        ),
    ]
