# Generated by Django 5.2.16 on 2026-08-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_classsubject_unique_together_and_more'),
        ('staff', '0003_teachingassignment_idx_assignment_teacher_and_more'),
        ('timetable', '0008_timetable_blocked_slots_timetable_day_periods_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='student_group',
            field=models.ForeignKey(blank=True, help_text='Student group/stream this teacher handles. Null = the full class cohort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments', to='timetable.studentgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'subject', 'academic_class', 'series', 'student_group', 'academic_year')},
        ),
    ]
