# Generated by Django 5.2.16 on 2026-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_class_fatigue_sensitivity_and_more'),
        ('staff', '0004_alter_teachingassignment_unique_together_and_more'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        ('timetable', '0011_teacheravailability'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['teacher', 'subject', 'academic_class'], name='idx_talloc_teacher_subj_cls'),
        ),
    ]
