# Generated by Django 5.2.16 on 2026-07-20 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly school identifier', max_length=100, unique=True)),
                ('education_type', models.CharField(choices=[('anglophone', 'Anglophone'), ('francophone', 'Francophone'), ('bilingual', 'Bilingual')], default='anglophone', max_length=20)),
                ('school_type', models.CharField(choices=[('general', 'General Education'), ('technical', 'Technical Education'), ('vocational', 'Vocational Education')], default='general', max_length=20)),
                ('session_type', models.CharField(choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session'), ('both', 'Morning & Afternoon')], default='morning', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Cameroon', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_config', models.JSONField(blank=True, default=dict, help_text='UI theme configuration: colors, fonts, etc.')),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('subscription_plan', models.CharField(default='starter', max_length=50)),
                ('max_students', models.IntegerField(default=500, help_text='Maximum students allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School (Tenant)',
                'verbose_name_plural': 'Schools (Tenants)',
                'db_table': 'tenants',
                'ordering': ['school_name'],
            },
        ),
    ]
