# Generated by Django 5.2.16 on 2026-07-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='tenants.tenant')),
                ('currency_code', models.CharField(default='XAF', help_text='ISO 4217 currency code', max_length=10)),
                ('currency_symbol', models.CharField(default='XAF', help_text='Display symbol', max_length=10)),
                ('grading_scale_max', models.DecimalField(decimal_places=1, default=20, help_text='Maximum possible score (e.g. 20 for French system, 100 for American)', max_digits=5)),
                ('grade_a_threshold', models.DecimalField(decimal_places=1, default=16, help_text='Minimum score for grade A', max_digits=5)),
                ('grade_b_threshold', models.DecimalField(decimal_places=1, default=12, help_text='Minimum score for grade B', max_digits=5)),
                ('grade_c_threshold', models.DecimalField(decimal_places=1, default=10, help_text='Minimum score for grade C', max_digits=5)),
                ('promotion_cutoff', models.DecimalField(decimal_places=1, default=9.5, help_text='Minimum average for student promotion', max_digits=5)),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='Available payment methods, e.g. ["mtn_momo", "orange_money", "bank_transfer"]')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5)),
                ('phone_format_placeholder', models.CharField(default='6XX XXX XXX', help_text='Placeholder text for phone number input', max_length=50)),
            ],
            options={
                'db_table': 'tenant_config',
            },
        ),
    ]
