# Generated by Django 5.2.16 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_tenant_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='idx_tenant_status'),
        ),
    ]
