# Generated by Django 5.2.16 on 2026-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_idx_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='finance_recording',
            field=models.CharField(choices=[('admin_and_bursar', 'Admin and Bursar'), ('bursar_only', 'Bursar Only')], default='admin_and_bursar', help_text='Who is allowed to RECORD financial transactions (payments, expenses, invoices). Bursar Only removes recording rights from school admins.', max_length=20),
        ),
    ]
