# Generated by Django 5.2.16 on 2026-07-20 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('documents', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Template', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('card_width', models.IntegerField(default=85, help_text='Card width in mm (standard: 85)')),
                ('card_height', models.IntegerField(default=54, help_text='Card height in mm (standard: 54)')),
                ('primary_color', models.CharField(default='#1a2b5f', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#d4a843', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'db_table': 'id_card_templates',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='academic.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_id_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_id_cards', to='tenants.tenant')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cards', to='documents.idcardtemplate')),
            ],
            options={
                'verbose_name': 'Generated ID Card',
                'verbose_name_plural': 'Generated ID Cards',
                'db_table': 'generated_id_cards',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'student', 'academic_year')},
            },
        ),
    ]
