# Generated by Django 5.2.16 on 2026-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_idcardtemplate_generatedidcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='style_config',
            field=models.JSONField(blank=True, default=dict, help_text='Full visual style configuration'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='accent_color',
            field=models.CharField(default='#F2B01E', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='primary_color',
            field=models.CharField(default='#0B2348', help_text='Hex color code', max_length=7),
        ),
    ]
