# Generated by Django 5.2.16 on 2026-08-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        ('staff', '0003_teachingassignment_idx_assignment_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='essential_knowledge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='expected_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='homework',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('taught', 'Taught')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='taught_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='taught_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_schemes', to='staff.teacher'),
        ),
    ]
