# Generated by Django 5.2.16 on 2026-08-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
        ('logbook', '0002_schemeofwork_essential_knowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummodule',
            name='academic_class',
            field=models.ForeignKey(blank=True, help_text='The class this scheme belongs to (e.g. Form 1).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='academic.class'),
        ),
    ]
