# Generated by Django 5.2.16 on 2026-08-19 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_curriculummodule_academic_class'),
        ('staff', '0005_add_production_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlesson',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who toggled this lesson completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who created this module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to='staff.teacher'),
        ),
    ]
