# Generated by Django 5.2.16 on 2026-07-20 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('registered', 'Registered (Pending)'), ('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='registered', max_length=20)),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.class')),
                ('series', models.ForeignKey(blank=True, help_text='2nd Cycle only: academic specialization (A, B, C, S1, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.series')),
                ('stream', models.ForeignKey(blank=True, help_text='Required for bilingual schools', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.stream')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.tenant')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('tenant', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Repeated'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_promoted_from', to='academic.class')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='tenants.tenant')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_promoted_to', to='academic.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
            ],
            options={
                'db_table': 'student_promotion_history',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('misconduct', 'Misconduct'), ('absenteeism', 'Absenteeism'), ('violence', 'Violence'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='students.student')),
            ],
            options={
                'db_table': 'student_discipline',
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_school', models.CharField(blank=True, max_length=255, null=True)),
                ('to_school', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
            ],
            options={
                'db_table': 'student_transfers',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'db_table': 'student_parent_links',
                'unique_together': {('parent_user', 'student')},
            },
        ),
    ]
