# Generated by Django 5.2.16 on 2026-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, help_text='e.g., A+, B-, O+', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency phone number', max_length=30),
        ),
    ]
