# Generated by Django 5.2.16 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
        ('students', '0003_rename_stream_to_section'),
        ('tenants', '0003_tenant_idx_tenant_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'current_class'], name='idx_student_class'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'status'], name='idx_student_status'),
        ),
    ]
