# Generated by Django 5.2.16 on 2026-08-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_idx_student_class_student_idx_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinerecord',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-date', '-id']},
        ),
    ]
