# Generated by Django 5.2.16 on 2026-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_class_fatigue_sensitivity_and_more'),
        ('students', '0006_student_middle_name'),
        ('tenants', '0004_tenantconfig_finance_recording'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'current_class', 'stream'], name='idx_student_cls_sec'),
        ),
    ]
