# Generated by Django 5.2.16 on 2026-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_alerts',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_alerts',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications'),
        ),
    ]
