# Generated by Django 5.2.16 on 2026-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolemapping',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'School Administrator'), ('bursar', 'Bursar'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('government', 'Government Officer')], max_length=20),
        ),
    ]
