# Generated by Django 5.2.16 on 2026-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Middle name(s), e.g., 'Nfon' in 'Dilan Nfon Ngongsong'", max_length=150),
        ),
    ]
