# Generated by Django 5.2.16 on 2026-08-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_invitation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_hash',
            field=models.CharField(blank=True, help_text="SHA-256 hash of the user's 6-digit PIN. Used for quick re-authentication.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last PIN change. Used to invalidate stale PIN verification tokens.', null=True),
        ),
    ]
