# Generated by Django 5.2.16 on 2026-07-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2026/2027', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Currently active year for the school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.tenant')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1st Cycle, 2nd Cycle', max_length=50)),
                ('order', models.PositiveSmallIntegerField(choices=[(1, '1st Cycle'), (2, '2nd Cycle')], help_text='1 for 1st Cycle, 2 for 2nd Cycle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'academic_cycles',
                'ordering': ['order'],
                'unique_together': {('tenant', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('anglophone', 'Anglophone Section'), ('francophone', 'Francophone Section')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tenants.tenant')),
            ],
            options={
                'db_table': 'academic_streams',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., A, S1, C, TI', max_length=10)),
                ('name', models.CharField(help_text='Full name of the series', max_length=255)),
                ('cycle', models.ForeignKey(help_text='Always 2nd Cycle', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='academic.cycle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='tenants.tenant')),
                ('stream', models.ForeignKey(blank=True, help_text='Required for bilingual schools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='academic.stream')),
            ],
            options={
                'db_table': 'academic_series',
                'ordering': ['cycle', 'code'],
                'unique_together': {('tenant', 'cycle', 'stream', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Form 1, 6ème, Seconde, Lower Sixth', max_length=50)),
                ('level_order', models.PositiveSmallIntegerField(help_text='Numeric order: 1=Form 1/6ème, ..., 7=Upper Sixth/Terminale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.tenant')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academic.cycle')),
                ('stream', models.ForeignKey(blank=True, help_text='Required for bilingual schools', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academic.stream')),
            ],
            options={
                'db_table': 'academic_classes',
                'ordering': ['cycle', 'stream', 'level_order', 'name'],
                'unique_together': {('tenant', 'cycle', 'stream', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Official exam code, e.g., 570 for GCE O-Level Maths', max_length=20)),
                ('default_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(blank=True, help_text='Null means available in all cycles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academic.cycle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'academic_subjects',
                'ordering': ['name'],
                'unique_together': {('tenant', 'cycle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Subject coefficient for this class/series', max_digits=4)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academic.class')),
                ('series', models.ForeignKey(blank=True, help_text='Only for 2nd cycle series-specific subjects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='academic.series')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academic.subject')),
            ],
            options={
                'db_table': 'academic_class_subjects',
                'unique_together': {('academic_class', 'subject', 'series')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1st Term', max_length=50)),
                ('order_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic.academicyear')),
            ],
            options={
                'db_table': 'academic_periods',
                'ordering': ['order_number'],
                'unique_together': {('academic_year', 'order_number')},
            },
        ),
    ]
