# Generated by Django 5.2.16 on 2026-07-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sequence 1, Sequence 2', max_length=50)),
                ('order_number', models.PositiveSmallIntegerField(help_text='Order within the term (1 or 2)')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='academic.term')),
            ],
            options={
                'db_table': 'academic_sequences',
                'ordering': ['term__order_number', 'order_number'],
                'unique_together': {('term', 'order_number')},
            },
        ),
    ]
