# Generated by Django 5.2.16 on 2026-07-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_rename_stream_to_section'),
        ('tenants', '0002_add_tenant_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German')], default='en', help_text='Primary language of instruction in this section', max_length=5),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='e.g., Anglophone, Francophone, Technical, Commercial', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.tenant'),
        ),
        migrations.AlterModelTable(
            name='section',
            table='academic_sections',
        ),
    ]
