# Generated by Django 5.2.16 on 2026-07-29 17:25

from django.db import migrations, models
from django.db.models import Max


def renumber_sequences_continuously(apps, schema_editor):
    """
    Renumber all existing sequences to be continuous across each academic year.
    Before: order_number resets per term (1,2 | 1,2 | 1,2)
    After:  order_number is continuous (1,2 | 3,4 | 5,6)
    """
    AcademicYear = apps.get_model('academic', 'AcademicYear')
    Sequence = apps.get_model('academic', 'Sequence')

    for year in AcademicYear.objects.all():
        sequences = (
            Sequence.objects.filter(term__academic_year=year)
            .select_related('term')
            .order_by('term__order_number', 'order_number', 'id')
        )
        for new_order, seq in enumerate(sequences, start=1):
            seq.order_number = new_order
            seq.name = f"Sequence {new_order}"
            seq.save(update_fields=['order_number', 'name'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_make_section_flexible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='order_number',
            field=models.PositiveSmallIntegerField(help_text='Continuous order across the academic year (1, 2, 3, ...)'),
        ),
        migrations.RunPython(
            renumber_sequences_continuously,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
