# Generated by Django 5.2.16 on 2026-08-02 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_academic_003_sequence_continuous_numbering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient of this subject within the section', max_digits=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='academic.subject')),
            ],
            options={
                'db_table': 'academic_section_subjects',
                'ordering': ['subject__name'],
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
