# Generated by Django 5.2.16 on 2026-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_sectionsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='weekly_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Official weekly hours (volume horaire) for this subject in this class. Used by the timetable generator.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_double_preferred',
            field=models.BooleanField(default=False, help_text='Sciences, languages and workshop subjects often run as 2 consecutive periods (double period)'),
        ),
    ]
