# Generated by Django 5.2.16 on 2026-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_classsubject_weekly_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='is_double',
            field=models.BooleanField(blank=True, help_text="Run this subject as double periods in this class. Empty = use the subject's default.", null=True),
        ),
    ]
