# Generated by Django 5.2.16 on 2026-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('grammar', 'Grammar'), ('technical', 'Technical'), ('commercial', 'Commercial')], default='grammar', help_text="Grammar (general academic), Technical, or Commercial. Decides which curriculum is auto-linked to the section's classes.", max_length=20),
        ),
    ]
