# Generated by Django 5.2.16 on 2026-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], default='', help_text='Subsystem this subject belongs to (English GCE / French MINESEC). Empty means shared or custom — shown for every section.', max_length=5),
        ),
    ]
