# Generated by Django 5.2.16 on 2026-08-13 21:21

from django.db import migrations


def _collect_catalog_language_maps():
    """Build code/name -> language maps from every curriculum catalog."""
    from apps.academic.curriculum import (
        ANGLOPHONE_SUBJECTS, FRANCOPHONE_SUBJECTS, CLASS_SUBJECTS,
    )
    codes = {'en': set(), 'fr': set()}
    names = {'en': set(), 'fr': set()}
    catalogs = [('en', ANGLOPHONE_SUBJECTS), ('fr', FRANCOPHONE_SUBJECTS)]
    for (section_type, language), levels in CLASS_SUBJECTS.items():
        flat = [entry for subjects in levels.values() for entry in subjects]
        catalogs.append((language, flat))
    for language, entries in catalogs:
        for entry in entries:
            name = entry[0]
            code = entry[1] or ''
            if code:
                codes[language].add(code)
            if name:
                names[language].add(name)
    return codes, names


def backfill_subject_language(apps, schema_editor):
    """Tag each master subject with the subsystem it belongs to (en/fr).

    Subjects matching both catalogs (or neither — custom/shared ones) keep an
    empty language so they remain visible for every section.
    """
    codes, names = _collect_catalog_language_maps()
    Subject = apps.get_model('academic', 'Subject')
    for subj in Subject.objects.all().iterator():
        code = subj.code or ''
        is_en = code in codes['en'] or subj.name in names['en']
        is_fr = code in codes['fr'] or subj.name in names['fr']
        if is_en and not is_fr:
            subj.language = 'en'
        elif is_fr and not is_en:
            subj.language = 'fr'
        else:
            subj.language = ''
        subj.save(update_fields=['language'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_subject_language'),
    ]

    operations = [
        migrations.RunPython(backfill_subject_language, migrations.RunPython.noop),
    ]
