# Generated by Django 5.2.16 on 2026-08-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_subject_language_backfill'),
        ('timetable', '0008_timetable_blocked_slots_timetable_day_periods_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='student_group',
            field=models.ForeignKey(blank=True, help_text='Student group/stream this allocation is for. Null = the full class cohort. Parallel groups let several subjects run at the same time in one class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='timetable.studentgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('academic_class', 'subject', 'series', 'student_group')},
        ),
    ]
