# Generated by Django 5.2.16 on 2026-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_classsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='fatigue_sensitivity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High')], default=3, help_text='How sensitive this class level is to cognitive fatigue. Younger classes (Form 1-2) should have higher sensitivity.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='afternoon_preference',
            field=models.PositiveSmallIntegerField(default=50, help_text='Preference score for afternoon periods (0-100). Higher = stronger preference.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='cognitive_demand',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='How much sustained concentration this subject requires. Affects scheduling preference for earlier periods.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='late_day_penalty',
            field=models.PositiveSmallIntegerField(default=30, help_text='Penalty score for late-day periods (0-100). Higher = stronger avoidance.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='morning_preference',
            field=models.PositiveSmallIntegerField(default=50, help_text='Preference score for morning periods (0-100). Higher = stronger preference.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_preference',
            field=models.CharField(choices=[('early', 'Early Day (Morning Preferred)'), ('middle', 'Middle Day'), ('late', 'Late Day (Afternoon Preferred)'), ('flexible', 'Flexible / Neutral')], default='flexible', help_text='Preferred time of day for this subject.', max_length=20),
        ),
    ]
