# Generated by Django 5.2.16 on 2026-07-20 01:04

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('academic', 'Academic Performance'), ('financial', 'Financial Summary'), ('attendance', 'Attendance Report'), ('compliance', 'Compliance & Audit'), ('comprehensive', 'Comprehensive')], default='comprehensive', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted_to_gov', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='academic.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='tenants.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='academic.term')),
            ],
            options={
                'db_table': 'school_performance_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_card_upload_path)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Scores and grades at generation time')),
                ('is_archived', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_cards', to='academic.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_cards', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_cards', to='academic.term')),
            ],
            options={
                'db_table': 'student_report_cards',
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
    ]
