# Generated by Django 5.2.16 on 2026-07-20 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Template', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#000000', help_text='Main accent color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#333333', help_text='Secondary text color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#F2B01E', help_text='Gold/highlight accent (hex)', max_length=7)),
                ('style_config', models.JSONField(blank=True, default=dict, help_text='Full visual style configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Report Card Template',
                'verbose_name_plural': 'Report Card Templates',
                'db_table': 'report_card_templates',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
