# Generated by Django 5.2.16 on 2026-07-23 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_add_sequence_model'),
        ('students', '0002_student_blood_group_student_emergency_contact'),
        ('tenants', '0002_add_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('termly', 'Term Exam'), ('bepc', 'BEPC'), ('gce_ol', 'GCE O-Level'), ('probatoire', 'Probatoire'), ('gce_al', 'GCE A-Level'), ('bac', 'Baccalauréat'), ('tvee_il', 'TVEE Intermediate Level'), ('tvee_al', 'TVEE Advanced Level')], default='termly', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of this term in the overall year (e.g., 33.33)', max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.term')),
            ],
            options={
                'db_table': 'assessment_exams',
                'ordering': ['term__order_number', 'name'],
                'unique_together': {('tenant', 'term')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., GCE O-Level, Baccalauréat', max_length=100)),
                ('sub_system', models.CharField(choices=[('anglophone', 'Anglophone'), ('francophone', 'Francophone')], max_length=20)),
                ('exam_level', models.CharField(choices=[('o_level', 'GCE O-Level'), ('a_level', 'GCE A-Level'), ('bac', 'Baccalauréat'), ('bepc', 'BEPC'), ('technical', 'Technical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_scales',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(help_text='e.g., A, B+, C, D, E, F, U, O', max_length=5)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum % or /20', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum % or /20', max_digits=5)),
                ('points', models.DecimalField(decimal_places=1, default=0, help_text='Points for this grade', max_digits=4)),
                ('description', models.CharField(blank=True, help_text='e.g., Excellent, Good, Fail', max_length=50)),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='assessments.gradescale')),
            ],
            options={
                'db_table': 'grade_boundaries',
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric score: /20 for Francophone, % for Anglophone', max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, help_text='A, B, C, D, E, F, U, O — for Anglophone grading', max_length=5)),
                ('points', models.DecimalField(blank=True, decimal_places=1, help_text='Grade points: O-Level max 3, A-Level max 5', max_digits=4, null=True)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.exam')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academic.sequence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academic.subject')),
            ],
            options={
                'db_table': 'assessment_results',
                'unique_together': {('exam', 'student', 'subject', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='MarkEntryWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_windows', to='academic.academicyear')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_windows', to='academic.sequence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_windows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assessment_mark_windows',
                'ordering': ['-academic_year__start_date', 'sequence__term__order_number', 'sequence__order_number'],
                'unique_together': {('tenant', 'sequence')},
            },
        ),
    ]
