# Generated by Django 5.2.16 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
        ('assessments', '0002_add_share_results_to_mark_entry_window'),
        ('students', '0003_rename_stream_to_section'),
        ('tenants', '0003_tenant_idx_tenant_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'term'], name='idx_exam_tenant_term'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['term'], name='idx_exam_term'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student', 'subject', 'sequence'], name='idx_result_lookup'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam'], name='idx_result_student_exam'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['sequence'], name='idx_result_sequence'),
        ),
        migrations.AddIndex(
            model_name='markentrywindow',
            index=models.Index(fields=['tenant', 'sequence'], name='idx_window_tenant_seq'),
        ),
        migrations.AddIndex(
            model_name='markentrywindow',
            index=models.Index(fields=['tenant', 'is_open'], name='idx_window_open'),
        ),
    ]
