# Generated by Django 5.2.16 on 2026-08-02 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_classsubject_weekly_hours_and_more'),
        ('staff', '0002_teacher_achievements_teacher_availability_and_more'),
        ('tenants', '0002_add_tenant_config'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked slots are kept untouched when the timetable is regenerated'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='generation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='generation_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='generation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('relaxed', 'Relaxed (has clashes)'), ('infeasible', 'Infeasible')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='periods',
            field=models.JSONField(default=list, help_text='School period template: list of {"start": "HH:MM", "end": "HH:MM"}'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='working_days',
            field=models.JSONField(default=list, help_text='Days of the week lessons run on, as day numbers (1=Monday ... 7=Sunday)'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1)),
                ('is_double', models.BooleanField(default=False, help_text='Run as 2 consecutive periods (science practical, languages, workshops)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='staff.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetable.timetable')),
            ],
            options={
                'db_table': 'timetable_lessons',
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_windows', to='staff.teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_unavailabilities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'timetable_teacher_unavailability',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
            },
        ),
    ]
