# Generated by Django 5.2.16 on 2026-08-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timeslot_is_locked_timetable_generation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The lesson card this slot belongs to (null for ad-hoc lessons)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='timetable.lesson'),
        ),
    ]
