# Generated by Django 5.2.16 on 2026-08-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timeslot_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
