# Generated by Django 5.2.16 on 2026-08-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='generation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('relaxed', 'Relaxed (has clashes)'), ('infeasible', 'Infeasible'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
