# Generated by Django 5.2.16 on 2026-08-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teachingassignment_idx_assignment_teacher_and_more'),
        ('timetable', '0005_alter_timetable_generation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='staff.teacher'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='staff.teacher'),
        ),
    ]
