# Generated by Django 5.2.16 on 2026-08-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classsubject_is_double'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        ('timetable', '0006_alter_lesson_teacher_alter_timeslot_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('tenant', 'academic_year', 'class_obj')},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.term'),
        ),
    ]
