# Generated by Django 5.2.16 on 2026-08-14 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_subject_language_backfill'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        ('timetable', '0007_alter_timetable_unique_together_alter_timetable_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='blocked_slots',
            field=models.JSONField(blank=True, default=list, help_text='First-class non-teaching blocks: [{day, start, end, label}] — breaks, lunch, assembly, chapel, staff meetings. No lesson may occupy them.'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_periods',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day period overrides (half-day support): {day_number: [periods]}. A day missing from this map uses the base `periods` template.'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited')),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('workshop', 'Workshop'), ('hall', 'Hall'), ('other', 'Other')], default='classroom', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.tenant')),
            ],
            options={
                'db_table': 'timetable_rooms',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Specific room/resource (lab, workshop...) when assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='timetable.room'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_full_cohort', models.BooleanField(default=False, help_text='This group contains every student of the class (like "Form 4").')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='academic.class')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='tenants.tenant')),
            ],
            options={
                'db_table': 'timetable_student_groups',
                'ordering': ['academic_class', 'order', 'name'],
                'unique_together': {('tenant', 'academic_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_group',
            field=models.ForeignKey(blank=True, help_text='Student group this lesson is for. Null = the full class cohort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='timetable.studentgroup'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='student_group',
            field=models.ForeignKey(blank=True, help_text='The student group attending this slot. Null = the full class cohort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='timetable.studentgroup'),
        ),
    ]
