# Generated by Django 5.2.16 on 2026-08-14 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_teachingassignment_unique_together_and_more'),
        ('timetable', '0008_timetable_blocked_slots_timetable_day_periods_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The user who approved/committed this timetable to the school schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='generation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('relaxed', 'Relaxed (has clashes)'), ('infeasible', 'Infeasible'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods', models.PositiveSmallIntegerField(default=0)),
                ('is_double', models.BooleanField(default=False, help_text="Run this teacher's share as 2 consecutive periods.")),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timetable.lesson')),
                ('teacher', models.ForeignKey(blank=True, help_text='NULL = unassigned placeholder (Teacher X / TBD), no real resource reserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='staff.teacher')),
            ],
            options={
                'db_table': 'timetable_teacher_allocations',
                'ordering': ['lesson', 'created_at'],
            },
        ),
    ]
