# Generated by Django 5.2.16 on 2026-08-14 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_timetable_approved_at_timetable_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="e.g., 'Pre-adjustment', 'Draft 1'", max_length=255)),
                ('slots_data', models.JSONField(help_text='Serialized list of all TimeSlots in this snapshot: [{day, start, end, subject, teacher, student_group, classroom}]')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='timetable.timetable')),
            ],
            options={
                'db_table': 'timetable_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
