# Generated by Django 5.2.16 on 2026-08-15 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_teachingassignment_unique_together_and_more'),
        ('tenants', '0004_tenantconfig_finance_recording'),
        ('timetable', '0010_timetablesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('whole_day', models.BooleanField(default=False, help_text='Covers the full school day (resolved against the current period grid)')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='staff.teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'timetable_teacher_availability',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
            },
        ),
    ]
