# Generated by Django 5.2.16 on 2026-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_class_fatigue_sensitivity_and_more'),
        ('staff', '0005_add_production_indexes'),
        ('timetable', '0011_teacheravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheravailability',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='timetablesnapshot',
            name='timetable',
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['timetable', 'day_of_week', 'start_time'], name='idx_timetable_entry_day_slot'),
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
        migrations.DeleteModel(
            name='TimetableSnapshot',
        ),
    ]
